spring:
  application:
    name: microservice-consumer-movie-ribbon
server:
  port: 8010
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    service-url:
      defaultZone: http://user:123@localhost:8761/eureka