spring:
  application:
    name: microservice-consumer-movie-ribbon-yaml-customizing
server:
  port: 8011
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    service-url:
      defaultZone: http://user:123@localhost:8761/eureka
ribbon:
  eureka:
    enabled: false
Microservice-provider-user:
  ribbon:
    listOfServers: localhost:7900
