server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false
    healthcheck:
      enabled: true
spring:
  security:
    user:
      name: user
      password: 123
